-- AlterTable
ALTER TABLE `PeriodicControl` MODIFY `frequency` ENUM('FIFTEEN_DAYS', 'MONTHLY', 'TWO_MONTHS', 'QUARTERLY', 'FOUR_MONTHS', 'FIVE_MONTHS', 'SEMI_ANNUALLY', 'SEVEN_MONTHS', 'EIGHT_MONTHS', 'NINE_MONTHS', 'TEN_MONTHS', 'ELEVEN_MONTHS', 'ANNUALLY') NOT NULL;
